In [ ]:
import os
from tqdm import tqdm
import pandas as pd
import pickle
tqdm.pandas()

In [ ]:


with open("data/df_train_prompt.pkl", "rb") as f:
    train_data = pickle.load(f)

with open("data/df_test_prompt.pkl", "rb") as f:
    test_data = pickle.load(f)

df = pd.read_csv('MIMIC/pesudo_mimic3_processed.csv')
icd_descript = pd.read_csv('MIMIC/ICD9_Descriptions.csv')

### Frequency

In [ ]:
train_data['condition'].values

array([list(['Mth sus Stph aur els/NOS', 'Human immuno virus dis', 'Pneumocystosis', 'Alkalosis', 'Cirrhosis of liver NOS', 'Bacteremia', 'Cachexia', 'Adv eff antiviral drugs', 'Inf mcrg rstn pncllins']),
       list(['Need prphyl vc vrl hepat', 'NB obsrv suspct infect', 'Single lb in-hosp w/o cs']),
       list(['NB transitory tachypnea', 'Fetal/neonatal jaund NOS', 'Need prphyl vc vrl hepat', 'NB obsrv suspct infect', 'Single lb in-hosp w cs', 'Routine circumcision']),
       ...,
       list(['Pure hyperglyceridemia', 'Ac posthemorrhag anemia', 'Dysthymic disorder', 'Hypertension NOS', 'Esophageal reflux', 'Hemoperitoneum', 'Intestinal disorder NOS', 'Pancreat cyst/pseudocyst', 'Intest malabsorption NOS', 'Acute kidney failure NOS', 'Nontrauma hema soft tiss', 'Complic med care NEC/NOS']),
       list(['DMII wo cmp nt st uncntr', 'Hyperlipidemia NEC/NOS', 'Ac posthemorrhag anemia', 'Crnry athrscl natve vssl', 'Aortic valve disorder', 'CHF NOS', 'Ac on chr diast hrt fail', 'Aortic atherosclerosis', 'Abdom aortic aneurysm', 'Malfunc vasc device/graf', 'Hemorrhage complic proc', 'Hematoma complic proc', 'Abn react-procedure NEC', 'Hx of breast malignancy', 'History of tobacco use', 'Aortocoronary bypass', 'Long-term use anticoagul']),
       list(['DMII wo cmp nt st uncntr', 'Hypertension NOS', 'Angina pectoris NEC/NOS', 'Spondylolisthesis', 'Stridor'])],
      dtype=object)

In [ ]:
all_string = ''
for conditions in train_data['condition'].values:
    try:
        for i in conditions:
            all_string = all_string +', '+ i
    except:
        print(i)

In [ ]:
from collections import Counter
combined_condition = all_string.split(', ')
all_condition = Counter(combined_condition)

condition = list(all_condition.keys())
count = list(all_condition.values())

df_count = pd.DataFrame({'condition': condition, 'count': count})

In [ ]:
df_count = df_count.sort_values(by='count', ascending=False)
df_count

                     condition  count
17            Hypertension NOS  18356
18                     CHF NOS  11509
52         Atrial fibrillation  11432
37    Crnry athrscl natve vssl  11146
21    Acute kidney failure NOS   8030
...                        ...    ...
6639            Photokeratitis      1
6640    Central origin vertigo      1
6641            Blister finger      1
6642           Tackle football      1
6643    Mal neo fallopian tube      1

[6677 rows x 2 columns]

In [ ]:
df_count['condition'] = df_count['condition'].apply(lambda x: x.lower())
df_count=df_count.dropna()
df_count = df_count.drop_duplicates()

In [ ]:
total = df_count['count'].sum()
df_count['ratio'] = df_count['count']/total*100

df_count

                     condition  count     ratio
17            hypertension nos  18356  3.189696
18                     chf nos  11509  1.999903
52         atrial fibrillation  11432  1.986523
37    crnry athrscl natve vssl  11146  1.936825
21    acute kidney failure nos   8030  1.395362
...                        ...    ...       ...
6639            photokeratitis      1  0.000174
6640    central origin vertigo      1  0.000174
6641            blister finger      1  0.000174
6642           tackle football      1  0.000174
6643    mal neo fallopian tube      1  0.000174

[6677 rows x 3 columns]

In [ ]:
df_count.describe()

              count        ratio
count   6677.000000  6677.000000
mean      86.188108     0.014977
std      486.928728     0.084613
min        1.000000     0.000174
25%        2.000000     0.000348
50%        6.000000     0.001043
75%       27.000000     0.004692
max    18356.000000     3.189696

In [ ]:
print(df_count[:100]['ratio'].sum())
general_conditions = list(df_count[:100]['condition'])

49.89556507807423

In [ ]:
(general_conditions)

['hypertension nos',
 'chf nos',
 'atrial fibrillation',
 'crnry athrscl natve vssl',
 'acute kidney failure nos',
 'dmii wo cmp nt st uncntr',
 'hyperlipidemia nec/nos',
 'acute respiratry failure',
 'urin tract infection nos',
 'esophageal reflux',
 'pure hypercholesterolem',
 'anemia nos',
 'hypothyroidism nos',
 'need prphyl vc vrl hepat',
 'pneumonia',
 'organism nos',
 'nb obsrv suspct infect',
 'ac posthemorrhag anemia',
 'acidosis',
 'chr airway obstruct nec',
 'severe sepsis',
 'long-term use anticoagul',
 'initial',
 'septicemia nos',
 'food/vomit pneumonitis',
 'chronic kidney dis nos',
 'hy kid nos w cr kid i-iv',
 'depressive disorder nec',
 'tobacco use disorder',
 'subendo infarct',
 'old myocardial infarct',
 'aortocoronary bypass',
 'pressure ulcer',
 'hyposmolality',
 'thrombocytopenia nos',
 'mitral valve disorder',
 'history of tobacco use',
 'single lb in-hosp w/o cs',
 'pleural effusion nos',
 'status-post ptca',
 'aortic valve disorder',
 'hyp kid nos w cr kid v',
 'long-term use of insulin',
 'septic shock',
 'cardiac dysrhythmias nec',
 'single lb in-hosp w cs',
 'obstructive sleep apnea',
 'surg compl-heart',
 'neonat jaund preterm del',
 'hyperosmolality',
 'ac kidny fail',
 'tubr necr',
 'asthma nos',
 'chr pulmon heart dis nec',
 'pulmonary collapse',
 'iatrogenc hypotnsion nec',
 'hyperpotassemia',
 'gout nos',
 'hypotension nos',
 'osteoporosis nos',
 'convulsions nec',
 'end stage renal disease',
 'parox ventric tachycard',
 'routine circumcision',
 'intermed coronary synd',
 'prim cardiomyopathy nec',
 'anxiety state nos',
 'hx-ven thrombosis/embols',
 'neuropathy in diabetes',
 'hemorrhage complic proc',
 'obesity nos',
 'cor ath unsp vsl ntv/gft',
 'bph w/o urinary obs/luts',
 'abn react-procedure nec',
 'bacteremia',
 'delirium d/t other cond',
 'int inf clstrdium dfcile',
 'hypopotassemia',
 'status cardiac pacemaker',
 'intracerebral hemorrhage',
 'init',
 'anemia in chr kidney dis',
 'gastrointest hemorr nos',
 'periph vascular dis nos',
 'abn react-surg proc nec',
 'dehydration',
 'hypovolemia',
 'cardiac arrest',
 'respiratory distress syn',
 'low back',
 'do not resusctate status',
 'hypoxemia',
 'chr diastolic hrt fail',
 'cirrhosis of liver nos',
 'hx of breast malignancy',
 'sepsis',
 'ac on chr diast hrt fail',
 'protein-cal malnutr nos',
 'hx-prostatic malignancy',
 'abn react-anastom/graft']

In [ ]:
df_train = train_data
df_train['overlap'] = df_train['condition'].apply(lambda x: sum(c.lower() in [word.lower() for word in x] for c in general_conditions))
df_train['overlap_ratio'] = df_train['overlap']/df_train['num']*100
df_train['a'] = 0
df_train

In [ ]:
df_train.describe()

         SUBJECT_ID           num       overlap  overlap_ratio        a
count  40354.000000  40354.000000  40354.000000   40354.000000  40354.0
mean   35387.021782     13.852778      5.692645      47.018485      0.0
std    28374.061354     15.287999      4.491099      23.703627      0.0
min        4.000000      1.000000      0.000000       0.000000      0.0
25%    13274.250000      6.000000      3.000000      31.250000      0.0
50%    25466.500000      9.000000      5.000000      45.454545      0.0
75%    57051.750000     16.000000      8.000000      62.500000      0.0
max    99999.000000    361.000000     50.000000     100.000000      0.0

In [ ]:
quantile_33 = df_train['overlap_ratio'].quantile(0.333)
quantile_67 = df_train['overlap_ratio'].quantile(0.667)
print(f"quantile_33: {quantile_33}, quantile_67: {quantile_67} ")

def classify_by_percentile(x):
    if x <= quantile_33:
        return 1
    elif x <= quantile_67:
        return 2
    else:
        return 3

df_train['a'] = df_train['overlap_ratio'].apply(classify_by_percentile)

In [ ]:
df_train = df_train[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'num']]
df_train.columns = ['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'condition_nums']

In [ ]:
df_train_1 = df_train[df_train['a']==1].sample(n=1333, replace=False, random_state=42)[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'condition_nums']]
df_train_2 = df_train[df_train['a']==2].sample(n=1333, replace=False, random_state=42)[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'condition_nums']]
df_train_3 = df_train[df_train['a']==3].sample(n=1334, replace=False, random_state=42)[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'condition_nums']]

sample_b = pd.concat([df_train_1,df_train_2,df_train_3], axis=0)
sample_b.a.value_counts()

a
3    1334
1    1333
2    1333
Name: count, dtype: int64

In [ ]:
sample_b.to_csv('sample_frequency_4000.csv', index=False)

### Length

In [ ]:
from datasets import load_dataset, Dataset, load_from_disk
import pandas as pd

with open("data/df_train_prompt.pkl", "rb") as f:
    train_data = pickle.load(f)

with open("data/df_test_prompt.pkl", "rb") as f:
    test_data = pickle.load(f)

df = pd.read_csv('MIMIC/pesudo_mimic3_processed.csv')
icd_descript = pd.read_csv('MIMIC/ICD9_Descriptions.csv')

In [ ]:
train_data = train_data.dropna()
train_data.head(5)

,SUBJECT_ID,name,gender,code,condition,num,answer,prompt
0,4,Wyman Maruca,F,"[04111, 042, 1363, 2763, 5715, 7907, 7994, E93...","[Mth sus Stph aur els/NOS, Human immuno virus ...",9,[Mth sus Stph aur els/NOS corresponds to 04111...,"As a medical expert, your task is to carefully..."
1,5,Marino Didomenico,M,"[V053, V290, V3000]","[Need prphyl vc vrl hepat, NB obsrv suspct inf...",3,"[Need prphyl vc vrl hepat corresponds to V053,...","As a medical expert, your task is to carefully..."
2,8,Elpidio Mcelrath,M,"[7706, 7746, V053, V290, V3001, V502]","[NB transitory tachypnea, Fetal/neonatal jaund...",6,"[NB transitory tachypnea corresponds to 7706, ...","As a medical expert, your task is to carefully..."
3,9,Lubertha Dansie,M,"[4019, 4280, 431, 5070, 5849]","[Hypertension NOS, CHF NOS, Intracerebral hemo...",5,"[Hypertension NOS corresponds to 4019, CHF NOS...","As a medical expert, your task is to carefully..."
4,10,Dwaine Hedglin,F,"[76515, 76525, 7742, V290, V3000]","[Preterm NEC 1250-1499g, 29-30 comp wks gestat...",5,"[Preterm NEC 1250-1499g corresponds to 76515, ...","As a medical expert, your task is to carefully..."

In [ ]:
df_sort = train_data.sort_values(by='num', ascending=False)
df_sort.head(5)

,SUBJECT_ID,name,gender,code,condition,num,answer,prompt
30024,55973,Odelia Worner,F,"[00845, 0088, 0088, 0380, 03842, 03842, 03842,...","[Int inf clstrdium dfcile, Viral enteritis NOS...",361,[Int inf clstrdium dfcile corresponds to 00845...,"As a medical expert, your task is to carefully..."
9887,13033,Tara Common,M,"[03849, 04111, 04119, 04119, 04119, 25011, 250...","[Gram-neg septicemia NEC, Mth sus Stph aur els...",350,"[Gram-neg septicemia NEC corresponds to 03849,...","As a medical expert, your task is to carefully..."
8945,11861,Dru Gill,F,"[0088, 0088, 0389, 04119, 04186, 04186, 04186,...","[Viral enteritis NOS, Viral enteritis NOS, Sep...",349,"[Viral enteritis NOS corresponds to 0088, Vira...","As a medical expert, your task is to carefully..."
34192,73713,Rickey Marciel,F,"[0380, 03812, 03849, 03849, 03849, 0389, 0389,...","[Streptococcal septicemia, MRSA septicemia, Gr...",330,"[Streptococcal septicemia corresponds to 0380,...","As a medical expert, your task is to carefully..."
23158,29035,Loralee Milkovich,F,"[00845, 0389, 0389, 0389, 0389, 0413, 0413, 04...","[Int inf clstrdium dfcile, Septicemia NOS, Sep...",323,[Int inf clstrdium dfcile corresponds to 00845...,"As a medical expert, your task is to carefully..."

In [ ]:
quantile_33 = df_sort['num'].quantile(0.333)
quantile_67 = df_sort['num'].quantile(0.667)
print(f"quantile_33: {quantile_33}, quantile_67: {quantile_67} ")
def classify_by_percentile(x):
    if x <= quantile_33:
        return 1
    elif x <= quantile_67:
        return 2
    else:
        return 3

df_sort['a'] = df_sort['num'].apply(classify_by_percentile)
print(df_sort[['num', 'a']])

quantile_33: 7.0, quantile_67: 13.0
       num  a
30024  361  3
9887   350  3
8945   349  3
34192  330  3
23158  323  3
...    ... ..
8398     1  1
8399     1  1
34140    1  1
1346     1  1
34182    1  1

[40354 rows x 2 columns]

In [ ]:
df_sort.describe()

         SUBJECT_ID           num             a
count  40354.000000  40354.000000  40354.000000
mean   35387.021782     13.852778      1.993854
std    28374.061354     15.287999      0.818656
min        4.000000      1.000000      1.000000
25%    13274.250000      6.000000      1.000000
50%    25466.500000      9.000000      2.000000
75%    57051.750000     16.000000      3.000000
max    99999.000000    361.000000      3.000000

In [ ]:
import random

df_train_1 = df_sort[df_sort['a']==1].sample(n=1333, replace=False, random_state=42)[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'num']]
df_train_2 = df_sort[df_sort['a']==2].sample(n=1333, replace=False, random_state=42)[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'num']]
df_train_3 = df_sort[df_sort['a']==3].sample(n=1334, replace=False, random_state=42)[['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'num']]

sample_c = pd.concat([df_train_1,df_train_2,df_train_3], axis=0)
sample_c.a.value_counts()

a
3    1334
1    1333
2    1333
Name: count, dtype: int64

In [ ]:
sample_c.columns = ['SUBJECT_ID', 'name', 'a', 'condition','code','gender', 'condition_nums']
sample_c.head(5)

,SUBJECT_ID,name,a,condition,code,gender,condition_nums
13598,17567,Lilla Falcon,1,"[Gram-neg septicemia NEC, Acidosis, Hyp kid NO...","[03849, 2762, 40391, 496, 515, 51881, 5849]",F,7
31961,64172,Alfreida Salaam,1,"[Hyperlipidemia NEC/NOS, Anxiety state NOS, Hy...","[2724, 30000, 4019, 41071, 41401, 4271]",F,6
20523,25878,Nyla Szostek,1,"[Preterm NEC 2000-2499g, 35-36 comp wks gestat...","[76518, 76528, 7706, V290, V3101]",M,5
37811,89236,Lorina Cruse,1,"[Herpes zoster NOS, DMII wo cmp nt st uncntr, ...","[0539, 25000, 4019, 5768, 5849, 5932, 5990]",F,7
27468,45276,Gertrude Seabury,1,"[Stenosis of larynx, Asthma NOS]","[47874, 49390]",F,2

In [ ]:
sample_c.to_csv('sample_length_4000.csv', index=False)

### Random

In [ ]:
train_path = "data/df_train_prompt.pkl"
test_path = "data/df_test_prompt.pkl"

print("### Load dataset")
with open(file=train_path, mode='rb') as f:
    train_dataset = pickle.load(f)

with open(file=test_path, mode='rb') as f:
    test_dataset = pickle.load(f)

In [ ]:
sample_4000 = train_dataset.sample(n=4000, replace=False, random_state=42)[['SUBJECT_ID', 'name','gender', 'code','condition', 'num']]
sample_4000.columns = ['SUBJECT_ID', 'name', 'gender', 'code','condition', 'condition_nums']
sample_4000.to_csv('sample_random_4000.csv', index=False)