In [1]:
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet
import pandas as pd
pd.set_option('display.max_rows', None)

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [2]:
syns=wordnet.synsets("fever.n.01")
for s in syns:
    print(s.name())

In [16]:
des = pd.read_csv('/content/MedCAT_Descriptions.csv')

In [17]:
des = des.drop_duplicates()
des = pd.DataFrame(des)
des.describe()

            CODE    DESCRIPTION
count       2672           2672
unique      2672           2672
top     C0000727  abdomen acute
freq           1              1

In [18]:
des['synonym'] = ''
des['syn_len'] = 0
des['DESCRIPTION'] = des['DESCRIPTION'].apply(lambda x: x.lower())
des['synonym'] = des['DESCRIPTION'].apply(lambda x: list(set([i.lemmas()[0].name() for i in wordnet.synsets(x)])))
des['synonym'] = des['synonym'].apply(lambda x: [i.replace('_', ' ') for i in x])
des['syn_len'] = des['synonym'].apply(lambda x: len(x))

In [19]:
des[des['syn_len']>0][:10]

        CODE      DESCRIPTION            synonym  syn_len
24  C0001816          agnosia          [agnosia]        1
25  C0001818      agoraphobia      [agoraphobia]        1
26  C0001824  agranulocytosis  [agranulocytosis]        1
27  C0001825         agraphia         [agraphia]        1
29  C0001916         albinism         [albinism]        1
33  C0002066              aku           [Yoruba]        1
35  C0002170         alopecia         [alopecia]        1
41  C0002418        amblyopia        [amblyopia]        1
42  C0002438        amebiasis        [amebiasis]        1
43  C0002453       amenorrhea       [amenorrhea]        1

In [20]:
def check_first_item(synonyms, description, syn_len):
    # Ensure the synonym list is not empty, syn_len is 1, and the first item matches the DESCRIPTION
    if syn_len == 1 and synonyms and synonyms[0].lower() == description.lower():
        return True
    return False

In [21]:
for index, row in des.iterrows():
    if check_first_item(row['synonym'], row['DESCRIPTION'], row['syn_len']):
        des.at[index, 'synonym'] = []

       CODE             DESCRIPTION synonym  syn_len
0  C0000727           abdomen acute      []        0
1  C0000737          abdominal pain      []        0
2  C0000809       habitual abortion      []        0
3  C0000814         missed abortion      []        0
4  C0000889    acanthosis nigricans      []        0
5  C0001125         acidosis lactic      []        0
6  C0001126  renal tubular acidosis      []        0
7  C0001127    respiratory acidoses      []        0
8  C0001144           acne vulgaris      []        0
9  C0001145             acne keloid      []        0

In [25]:
non_empty_synonym_rows = des[des['synonym'].apply(lambda x: len(x) != 0)]

In [31]:
non_empty_synonym_rows.to_csv('non_empty_synonym_rows.csv', index=False)

In [32]:
non_empty_synonym_rows

,CODE,DESCRIPTION,synonym,syn_len
33,C0002066,aku,[Yoruba],1
50,C0002871,anemia,"[Anemia, anemia]",2
174,C0007398,catatonia,"[catatonic schizophrenia, catatonia]",2
188,C0007947,chancroids,[chancroid],1
195,C0008058,chilblains,[chilblain],1
205,C0008489,chorea,"[canine chorea, chorea]",2
214,C0009090,cluttering,[clutter],1
235,C0009806,constipation,"[stultification, constipation]",2
246,C0010200,coughing,[cough],1
252,C0010380,croup,"[croup, hindquarters]",2
272,C0011206,delirium,"[craze, delirium]",2
292,C0011636,dermatophytosis,[dermatomycosis],1
322,C0013395,dyspepsia,[indigestion],1
359,C0014724,eructation,"[eruption, belch]",2
376,C0014877,esotropia,[cross-eye],1
379,C0015230,exanthema,[exanthem],1
394,C0015672,fatigue,"[fatigue, fatigue duty, tire]",3
408,C0016204,flatulence,"[flatulence, turgidity]",2
409,C0016382,flushing,"[sluice, blush, flush]",3
455,C0018524,hallucinations,"[delusion, hallucination]",2
458,C0018681,headache,"[headache, concern]",2
470,C0018934,haematocolpos,[hematocolpos],1
488,C0019112,hemorrhoids,[hemorrhoid],1
519,C0019825,hoarseness,[gruffness],1
521,C0019917,hordeolum,[sty],1
529,C0020428,hyperaldosteronism,[aldosteronism],1
537,C0020473,hyperlipidemia,[lipemia],1
541,C0020490,farsighted,"[farsighted, farseeing]",2
589,C0022346,icterus,"[Icterus, jaundice]",2
628,C0023321,lentigo,[freckle],1
631,C0023364,leptospirosis,[swamp fever],1
634,C0023380,lethargy,"[languor, inanition, lethargy]",3
672,C0024312,lymphopenia,[lymphocytopenia],1
717,C0026113,miliaria,[prickly heat],1
721,C0026351,imbecile,"[imbecile, idiot]",2
743,C0027059,myocarditis,[myocardial inflammation],1
766,C0027769,nervousness,"[jitteriness, nervousness]",2
778,C0028084,nightmares,[nightmare],1
783,C0028754,obesity,[fleshiness],1
828,C0030193,pain,"[pain, trouble, annoyance]",3
875,C0031099,periodontitis,[periodontal disease],1
880,C0031256,petechiae,[petechia],1
889,C0032064,plague,"[harass, blight, plague, infestation]",4
976,C0035435,rheumatism,"[rheumatism, rheumatoid arthritis]",2
984,C0035854,rosacea,[acne rosacea],1
985,C0035920,rubella,[German measles],1
1006,C0036474,scurvy,"[scurvy, abject]",2
1011,C0036690,septicemia,[blood poisoning],1
1033,C0037384,snoring,[snore],1
1035,C0037672,somnambulism,[sleepwalking],1
1068,C0038506,stuttering,[bumble],1
1074,C0039070,syncope,"[syncope, faint]",2
1103,C0040156,thyrotoxicosis,[hyperthyroidism],1
1106,C0040247,tinea,"[Tinea, tinea]",2
1153,C0042109,urticaria,[urtication],1
1164,C0042571,vertigo,[dizziness],1
1181,C0042963,vomiting,[vomit],1
1189,C0043144,wheezing,"[wheeze, asthmatic]",2
1191,C0043167,pertussis,[whooping cough],1
1196,C0043388,yaws,"[yaw, gape, yaws]",3
1237,C0085584,encephalopathies,[brain disorder],1
1238,C0085593,chills,"[chill, frisson, cool]",3
1246,C0085628,stupor,"[grogginess, daze]",2
1580,C0220870,lightheadedness,"[dizziness, lightheadedness]",2
1633,C0233728,lisp,"[lisp, LISP]",2
1718,C0242301,furuncle,[boil],1
2050,C0338831,manic,[frenzied],1
2256,C0494491,mononeuropathies,[mononeuropathy],1
2426,C0878544,cardiomyopathies,[cardiomyopathy],1
2431,C0917801,sleeplessness,[wakefulness],1
2450,C1142436,sundown,[sunset],1
2490,C1328840,alps,"[alp, Alps]",2
2509,C1442903,exostoses,[exostosis],1
2615,C2830004,somnolence,[sleepiness],1
2659,C3714552,weakness,"[helplessness, weakness, failing]",3
2665,C4048158,convulsions,"[convulsion, paroxysm]",2

In [ ]:

df = des[des['drop_synonym'] == False].drop('synonym', axis=1)
# Drop the 'synonym' column where condition is True
df = des.drop('drop_synonym', axis=1)

In [ ]:
des.to_csv('synonym_condition.csv', index = False)